<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "game".
 *
 * @property int $id
 * @property string $name_is
 * @property string $name_en
 * @property string $key
 * @property string $qr
 * @property string $question_is
 * @property string $question_en
 * @property string $description_is
 * @property string $description_en
 * @property string $photo
 * @property string $video
 * @property string $icon
 * @property string $lat
 * @property string $lon
 * @property string $map
 */
class Game extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'game';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['question_is', 'question_en', 'description_is', 'description_en'], 'string'],
            [['name_is', 'name_en', 'key', 'qr'], 'string', 'max' => 300],
            [['photo', 'video', 'icon'], 'string', 'max' => 150],
            [['lat', 'lon'], 'string', 'max' => 50],
            [['map'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name_is' => 'Name Is',
            'name_en' => 'Name En',
            'key' => 'Key',
            'qr' => 'Qr',
            'question_is' => 'Question Is',
            'question_en' => 'Question En',
            'description_is' => 'Description Is',
            'description_en' => 'Description En',
            'photo' => 'Photo',
            'video' => 'Video',
            'icon' => 'Icon',
            'lat' => 'Lat',
            'lon' => 'Lon',
            'map' => 'Map',
        ];
    }

    public function beforeSave($insert)
    {
        if(!$this->key){
            $this->key = Yii::$app->security->generateRandomString(64);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
