<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "safnanott_user".
 *
 * @property int $id
 * @property string|null $key
 * @property string|null $phone
 * @property string|null $name
 * @property string|null $created
 */
class SafnanottUser extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'safnanott_user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created'], 'safe'],
            [['key'], 'string', 'max' => 255],
            [['phone'], 'string', 'max' => 50],
            [['name'], 'string', 'max' => 150],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'key' => 'Key',
            'phone' => 'Phone',
            'name' => 'Name',
            'created' => 'Created',
        ];
    }

    public function beforeSave($insert)
    {
        if(!$this->key){
            $this->key = Yii::$app->security->generateRandomString(64);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
