<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "safnanott".
 *
 * @property int $id
 * @property string|null $title
 * @property string|null $logo
 * @property string|null $image
 * @property string|null $image_big
 * @property string|null $description
 * @property string|null $question
 * @property string|null $lat
 * @property string|null $lon
 * @property string|null $address
 * @property string|null $site
 * @property string|null $phone
 * @property string|null $key
 * @property string|null $created
 */
class Safnanott extends \yii\db\ActiveRecord
{
    public $map;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'safnanott';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['description', 'question'], 'string'],
            [['created'], 'safe'],
            [['title', 'key'], 'string', 'max' => 300],
            [['lat', 'lon', 'address', 'phone'], 'string', 'max' => 20],
            [['site'], 'string', 'max' => 150],
            [['logo', 'image', 'image_big'], 'file', 'skipOnEmpty' => true],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'logo' => 'Logo',
            'image' => 'Image',
            'image_big' => 'Image Big',
            'description' => 'Description',
            'question' => 'Question',
            'lat' => 'Lat',
            'lon' => 'Lon',
            'address' => 'Address',
            'site' => 'Site',
            'phone' => 'Phone',
            'key' => 'Key',
            'created' => 'Created',
        ];
    }

    public function beforeSave($insert)
    {
        if(!$this->key){
            $this->key = Yii::$app->security->generateRandomString(64);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->logo = \yii\helpers\Url::to('/img/safnanott/' . $this->logo, true);
        $this->image = \yii\helpers\Url::to('/img/safnanott/image/' . $this->image, true);
        $this->image_big = \yii\helpers\Url::to('/img/safnanott/image_big/' . $this->image_big, true);
        $this->map = "https://www.google.com/maps/dir/Current location/".$this->lat.",".$this->lon;
    }

    public function fields()
    {
        $fields = parent::fields();
        $fields[] = 'map';
        return $fields;
   }
}
